package web

// prefs_golden_test.go pins the ro_prefs codec to a BYTE-EXACT wire contract
// via JSON golden fixtures shared with the JS writer (readout.js). The fixtures
// in testdata/prefs_golden/ carry hand-authored `encoded` literals derived from
// the JS codec's semantics (compact JSON, NO HTML escaping, base64url over the
// UTF-8 bytes) -- they are deliberately NOT generated by the Go codec, so they
// catch any divergence between the two writers instead of rubber-stamping it.
//
// The historical divergence these fixtures lock down: Go's json.Marshal
// HTML-escapes < > & to < > & while JS's JSON.stringify leaves
// them literal, so the two codecs emitted DIFFERENT cookie strings for CRD
// column names carrying those characters. The contract is byte identity of the
// encoded cookie VALUE ("v1." + base64url), not decode-equality.
//
// Fixture classes (see each file's "doc"): simple payload; UTF-8 CRD column
// names; < > & metachars (the bug); the at-cap boundary; over-cap eviction
// (ASCII) with documented victims; over-cap eviction (multibyte) pinning the
// byte-vs-UTF-16-code-unit cap equivalence; and corrupt decode inputs.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

const prefsGoldenDir = "testdata/prefs_golden"

// goldenEncodeFixture is the encode-direction shape: a prefs payload and the
// canonical cookie value it must produce byte-for-byte. The over-cap fixtures
// additionally record the kinds the eviction loop must drop / keep, asserted
// against the decoded result so the chosen victims are pinned (both codecs must
// evict the same tail entries).
type goldenEncodeFixture struct {
	Doc     string   `json:"doc"`
	Payload *prefs   `json:"payload"`
	Encoded string   `json:"encoded"`
	Evicted []string `json:"evicted"`
	Kept    []string `json:"kept"`
}

// goldenDecodeFixture is the decode-direction shape: malformed cookie values
// that must yield empty prefs (ok=false), mirroring readout.js readPrefs.
type goldenDecodeFixture struct {
	Doc         string `json:"doc"`
	DecodeCases []struct {
		Why    string `json:"why"`
		Value  string `json:"value"`
		WantOK bool   `json:"want_ok"`
	} `json:"decode_cases"`
}

// readGoldenFile reads and JSON-decodes one fixture file into dst.
func readGoldenFile(t *testing.T, name string, dst any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(prefsGoldenDir, name))
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	if err := json.Unmarshal(raw, dst); err != nil {
		t.Fatalf("decode fixture %s: %v", name, err)
	}
}

// TestPrefsGoldenEncode is the byte-exact encode contract: every encode-direction
// fixture's hand-authored `encoded` literal must equal encodePrefs(payload).
// The 03_html_metachars fixture is the one that fails against an HTML-escaping
// Go codec.
func TestPrefsGoldenEncode(t *testing.T) {
	encodeFiles := []string{
		"01_simple.json",
		"02_utf8_crd_columns.json",
		"03_html_metachars.json",
		"04_at_cap_boundary.json",
		"05_over_cap_eviction.json",
		"06_over_cap_multibyte.json",
	}
	for _, name := range encodeFiles {
		t.Run(name, func(t *testing.T) {
			var fx goldenEncodeFixture
			readGoldenFile(t, name, &fx)
			if fx.Payload == nil {
				t.Fatalf("%s: no payload", name)
			}
			got := encodePrefs(*fx.Payload)
			if got != fx.Encoded {
				t.Errorf("%s: encodePrefs byte mismatch\n got = %q\nwant = %q", name, got, fx.Encoded)
			}
			// The encoded value must always satisfy the cap.
			if len(got) > prefsMaxEncoded {
				t.Errorf("%s: encoded length %d exceeds cap %d", name, len(got), prefsMaxEncoded)
			}
			// Over-cap fixtures pin which tail kinds survived: decode the golden
			// value back and check the kept set matches (eviction determinism).
			if len(fx.Kept) > 0 {
				p, ok := decodePrefs(fx.Encoded)
				if !ok {
					t.Fatalf("%s: golden encoded value did not decode", name)
				}
				gotKept := make([]string, len(p.Kinds))
				for i := range p.Kinds {
					gotKept[i] = p.Kinds[i].Plural
				}
				if !equalStrings(gotKept, fx.Kept) {
					t.Errorf("%s: surviving kinds = %v, want %v (evicted %v)", name, gotKept, fx.Kept, fx.Evicted)
				}
			}
		})
	}
}

// TestPrefsGoldenDecodeCorrupt pins the lenient decode floor: corrupt cookie
// values yield empty prefs with ok=false, never an error.
func TestPrefsGoldenDecodeCorrupt(t *testing.T) {
	var fx goldenDecodeFixture
	readGoldenFile(t, "07_corrupt_decode.json", &fx)
	if len(fx.DecodeCases) == 0 {
		t.Fatal("07_corrupt_decode.json: no decode cases")
	}
	for _, c := range fx.DecodeCases {
		t.Run(c.Why, func(t *testing.T) {
			p, ok := decodePrefs(c.Value)
			if ok != c.WantOK {
				t.Errorf("decodePrefs(%q) ok = %v, want %v", c.Value, ok, c.WantOK)
			}
			if !ok && (len(p.Kinds) != 0 || p.Refresh != "" || len(p.Namespaces) != 0) {
				t.Errorf("decodePrefs(%q) returned non-empty prefs %+v on failure", c.Value, p)
			}
		})
	}
}

// equalStrings reports whether two string slices are element-wise equal.
func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
