apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "readout.name" . }}
  labels:
    {{- include "readout.labels" . | nindent 4 }}
data:
  readout.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
