{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "readout.fullname" . }}
  labels:
    {{- include "readout.labels" . | nindent 4 }}
  {{- $ann := include "readout.annotations" (dict "context" .) }}
  {{- with $ann }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "readout.selectorLabels" . | nindent 6 }}
{{- end }}
