apiVersion: v1
kind: Service
metadata:
  name: {{ include "readout.name" . }}
  labels:
    {{- include "readout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    application: {{ include "readout.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
