// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/kbelokon/readout/internal/version"
	"github.com/kbelokon/readout/internal/web/icons"
)

// components.templ holds the shared templ building blocks the page bodies and
// the layout reuse: the inline-SVG icon wrapper, the command-palette overlay +
// its row <template>, and the small ro-chip / CRD-badge / boolean pill
// fragments. Trusted raw HTML (the Lucide SVGs) is emitted via templ.Raw; every
// data value goes through templ's contextual auto-escaping. The DOM these emit
// is pinned by the behavior-fact net.

// iconC renders an inline Lucide SVG by name. The SVG markup is trusted,
// build-time-constant chrome (no user data), so it is emitted raw.
func iconC(name string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(icons.SVG(name)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// chipKey is one label/annotation chip key=value class fragment; templ adds the
// " ro-label-app" suffix for app.kubernetes.io/* keys via appLabelClassC.

// CommandPalette is the ⌘K jump-to overlay, included once per page in the
// layout. It owns no data: readout.js reads the server-built #ro-palette-data
// JSON blob (D10) and builds the grouped rows into #ro-palette-list at open
// time. The overlay ROOT carries BOTH `ro-rd` AND `ro-palette-backdrop` (D13:
// the redesign palette container rules are gated by the `ro-rd` marker ON the
// backdrop root, since the overlay lives OUTSIDE the `.ro-rd` content subtree);
// readout.js toggles the `open` class to reveal it. The ids/classes/roles here
// are a hard JS contract -- the search input, the list container, and the
// `.ro-pal-*` row vocabulary the JS writes into must match base.css + the JS.
func CommandPalette() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"ro-palette\" class=\"ro-rd ro-palette-backdrop\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Jump to\" aria-hidden=\"true\"><div class=\"ro-palette\" role=\"document\"><div class=\"ro-pal-search\"><span class=\"ico\" aria-hidden=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = iconC("search").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span><input id=\"ro-palette-input\" type=\"text\" placeholder=\"Jump to a cluster, namespace, resource type, or action…\" autocomplete=\"off\" autocorrect=\"off\" autocapitalize=\"off\" spellcheck=\"false\" role=\"combobox\" aria-expanded=\"true\" aria-controls=\"ro-palette-list\" aria-autocomplete=\"list\" aria-label=\"Jump to\"><span id=\"ro-palette-scope\" class=\"ro-pal-scope\" aria-hidden=\"true\" hidden></span></div><div id=\"ro-palette-list\" class=\"ro-pal-list\" role=\"listbox\" aria-label=\"Jump targets\"></div><div class=\"ro-pal-foot\"><span class=\"hint\"><kbd class=\"ro-kbd\">&#8593;</kbd><kbd class=\"ro-kbd\">&#8595;</kbd> navigate</span><span class=\"hint\"><kbd class=\"ro-kbd\">&#8629;</kbd> open</span><span class=\"hint\"><kbd class=\"ro-kbd\">esc</kbd> close</span><span class=\"spacer\"></span><span class=\"hint\">readout</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// defaultFooter is the built-in footer (the app name + version), rendered when
// no TemplatesPath footer override is set. It carries NO upstream attribution or
// outbound credit link -- attribution lives only in LICENSE/NOTICE/README.
func defaultFooter() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<footer class=\"footer ro-footer\"><div class=\"container\"><div class=\"ro-footer-copy\"><p>readout ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(version.Version)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 41, Col: 113}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
